[package]
name = "y-crdt-jni"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "ycrdt_jni"

[dependencies]
jni = "0.21.1"
yrs = "0.25.0"
lazy_static = "1.4.0"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
